// Code generated by go-swagger; DO NOT EDIT.

package read_items

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetItemByIDParams creates a new GetItemByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetItemByIDParams() *GetItemByIDParams {
	return &GetItemByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetItemByIDParamsWithTimeout creates a new GetItemByIDParams object
// with the ability to set a timeout on a request.
func NewGetItemByIDParamsWithTimeout(timeout time.Duration) *GetItemByIDParams {
	return &GetItemByIDParams{
		timeout: timeout,
	}
}

// NewGetItemByIDParamsWithContext creates a new GetItemByIDParams object
// with the ability to set a context for a request.
func NewGetItemByIDParamsWithContext(ctx context.Context) *GetItemByIDParams {
	return &GetItemByIDParams{
		Context: ctx,
	}
}

// NewGetItemByIDParamsWithHTTPClient creates a new GetItemByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetItemByIDParamsWithHTTPClient(client *http.Client) *GetItemByIDParams {
	return &GetItemByIDParams{
		HTTPClient: client,
	}
}

/* GetItemByIDParams contains all the parameters to send to the API endpoint
   for the get item by Id operation.

   Typically these are written to a http.Request.
*/
type GetItemByIDParams struct {

	// ItemID.
	//
	// Format: int64
	ItemID int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get item by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetItemByIDParams) WithDefaults() *GetItemByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get item by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetItemByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get item by Id params
func (o *GetItemByIDParams) WithTimeout(timeout time.Duration) *GetItemByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get item by Id params
func (o *GetItemByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get item by Id params
func (o *GetItemByIDParams) WithContext(ctx context.Context) *GetItemByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get item by Id params
func (o *GetItemByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get item by Id params
func (o *GetItemByIDParams) WithHTTPClient(client *http.Client) *GetItemByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get item by Id params
func (o *GetItemByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithItemID adds the itemID to the get item by Id params
func (o *GetItemByIDParams) WithItemID(itemID int64) *GetItemByIDParams {
	o.SetItemID(itemID)
	return o
}

// SetItemID adds the itemId to the get item by Id params
func (o *GetItemByIDParams) SetItemID(itemID int64) {
	o.ItemID = itemID
}

// WriteToRequest writes these params to a swagger request
func (o *GetItemByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param itemId
	if err := r.SetPathParam("itemId", swag.FormatInt64(o.ItemID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
