// Code generated by go-swagger; DO NOT EDIT.

package item

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"go-server-server/lostfound/models"
)

// CreateItemReader is a Reader for the CreateItem structure.
type CreateItemReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateItemReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewCreateItemCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewCreateItemBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewCreateItemCreated creates a CreateItemCreated with default headers values
func NewCreateItemCreated() *CreateItemCreated {
	return &CreateItemCreated{}
}

/* CreateItemCreated describes a response with status code 201, with default header values.

Item Created
*/
type CreateItemCreated struct {
	Payload *models.Item
}

func (o *CreateItemCreated) Error() string {
	return fmt.Sprintf("[POST /items][%d] createItemCreated  %+v", 201, o.Payload)
}
func (o *CreateItemCreated) GetPayload() *models.Item {
	return o.Payload
}

func (o *CreateItemCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Item)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateItemBadRequest creates a CreateItemBadRequest with default headers values
func NewCreateItemBadRequest() *CreateItemBadRequest {
	return &CreateItemBadRequest{}
}

/* CreateItemBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type CreateItemBadRequest struct {
}

func (o *CreateItemBadRequest) Error() string {
	return fmt.Sprintf("[POST /items][%d] createItemBadRequest ", 400)
}

func (o *CreateItemBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
